In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [21]:
# import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

In [3]:
df=pd.read_csv("bank.csv")

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#Row Number, Surname and CustomerID columns can be dropped
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [6]:
df.head()
df["Geography"].unique()
df["Gender"].unique()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

array(['France', 'Spain', 'Germany'], dtype=object)

array(['Female', 'Male'], dtype=object)

In [7]:
X = df.iloc[:,0:10].values
y = df.iloc[:, 10].values

In [8]:
X
y

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
#label_X_country_encoder.fit_transform(X[:,1])

In [11]:
# Encoding categorical (string based) data. Country: there are 3 options: France, Spain and Germany
# This will convert those strings into scalar values for analysis
#print(X[:8,1], '... will now become: ')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_country_encoder = LabelEncoder()
X[:,1] = label_X_country_encoder.fit_transform(X[:,1])


In [12]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
# We will do the same thing for gender. this will be binary in this dataset

label_X_gender_encoder = LabelEncoder()
X[:,2] = label_X_gender_encoder.fit_transform(X[:,2])


In [14]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
countryhotencoder = OneHotEncoder(categorical_features=[1]) # 1 is the country column
X=countryhotencoder.fit_transform(X).toarray()

C:\Users\kalya\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\kalya\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [17]:

# Splitting the dataset into the Training and Testing set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [103]:
# import keras

In [22]:
# from keras.models import Sequential
# from keras.layers import Dense

In [19]:
#Initialize Sequential model
# model = Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
# model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
# model.add(keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
# model.add(Dense(1, activation='relu'))

#Comile the model ((We will learn about optimizers it in the next residency))
# model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [23]:
model = Sequential()
model.add(Dense(activation = 'relu', input_dim = 12, units=6, kernel_initializer='uniform'))
model.add(keras.layers.BatchNormalization())
model.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [24]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Train on 7000 samples, validate on 3000 samples
Epoch 1/100
7000/7000 [==============================] - 2s 249us/step - loss: 0.5023 - acc: 0.7964 - val_loss: 0.4311 - val_acc: 0.7930
Epoch 2/100
7000/7000 [==============================] - 1s 127us/step - loss: 0.4304 - acc: 0.7977 - val_loss: 0.4150 - val_acc: 0.7930
Epoch 3/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.4110 - acc: 0.7977 - val_loss: 0.3993 - val_acc: 0.7930
Epoch 4/100
7000/7000 [==============================] - 1s 127us/step - loss: 0.3967 - acc: 0.8256 - val_loss: 0.3696 - val_acc: 0.8460
Epoch 5/100
7000/7000 [==============================] - 1s 123us/step - loss: 0.3842 - acc: 0.8397 - val_loss: 0.3545 - val_acc: 0.8473
Epoch 6/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.3765 - acc: 0.8457 - val_loss: 0.3515 - val_acc: 0.8520
Epoch 7/100
7000/7000 [==============================] - 1s 126us/step - loss: 0.3

7000/7000 [==============================] - 1s 115us/step - loss: 0.3556 - acc: 0.8551 - val_loss: 0.3388 - val_acc: 0.8607
Epoch 59/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3502 - acc: 0.8571 - val_loss: 0.3431 - val_acc: 0.8533
Epoch 60/100
7000/7000 [==============================] - 1s 133us/step - loss: 0.3543 - acc: 0.8530 - val_loss: 0.3423 - val_acc: 0.8600
Epoch 61/100
7000/7000 [==============================] - 1s 144us/step - loss: 0.3570 - acc: 0.8543 - val_loss: 0.3478 - val_acc: 0.8590
Epoch 62/100
7000/7000 [==============================] - 1s 142us/step - loss: 0.3536 - acc: 0.8530 - val_loss: 0.3419 - val_acc: 0.8590
Epoch 63/100
7000/7000 [==============================] - 1s 141us/step - loss: 0.3517 - acc: 0.8596 - val_loss: 0.3397 - val_acc: 0.8587
Epoch 64/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3544 - acc: 0.8563 - val_loss: 0.3445 - val_acc: 0.8583
Epoch 65/100
7000/7000 [=======================

In [25]:
model.predict(X_test)

array([[0.2596135 ],
       [0.27017164],
       [0.19322124],
       ...,
       [0.11883569],
       [0.08246106],
       [0.62185633]], dtype=float32)

In [26]:
y_predict=model.predict_classes(X_test)

In [27]:
from sklearn import metrics

In [28]:
metrics.accuracy_score(y_test,y_predict)

0.8603333333333333

In [29]:
metrics.confusion_matrix(y_test,y_predict)

array([[2273,  106],
       [ 313,  308]], dtype=int64)

In [30]:
cr=metrics.classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2379
           1       0.74      0.50      0.60       621

   micro avg       0.86      0.86      0.86      3000
   macro avg       0.81      0.73      0.76      3000
weighted avg       0.85      0.86      0.85      3000



In [31]:
from keras.optimizers import sgd

In [34]:
model = Sequential()
model.add(Dense(activation = 'relu', input_dim = 12, units=6, kernel_initializer='uniform'))
model.add(keras.layers.BatchNormalization())
model.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 

sg = sgd(lr=0.5)


model.compile(optimizer=sg, loss = 'binary_crossentropy', metrics=['accuracy'])

In [35]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=10, epochs=100)

Train on 7000 samples, validate on 3000 samples
Epoch 1/100
7000/7000 [==============================] - 2s 299us/step - loss: 0.4413 - acc: 0.8069 - val_loss: 0.3843 - val_acc: 0.8400
Epoch 2/100
7000/7000 [==============================] - 1s 166us/step - loss: 0.4134 - acc: 0.8233 - val_loss: 0.3840 - val_acc: 0.8437
Epoch 3/100
7000/7000 [==============================] - 1s 168us/step - loss: 0.3996 - acc: 0.8320 - val_loss: 0.3739 - val_acc: 0.8410
Epoch 4/100
7000/7000 [==============================] - 1s 166us/step - loss: 0.4012 - acc: 0.8307 - val_loss: 0.3774 - val_acc: 0.8420
Epoch 5/100
7000/7000 [==============================] - 1s 165us/step - loss: 0.3963 - acc: 0.8324 - val_loss: 0.3895 - val_acc: 0.8460
Epoch 6/100
7000/7000 [==============================] - 1s 162us/step - loss: 0.4006 - acc: 0.8326 - val_loss: 0.3560 - val_acc: 0.8573
Epoch 7/100
7000/7000 [==============================] - 1s 160us/step - loss: 0.3945 - acc: 0.8334 - val_loss: 0.3615 - val_acc: 

Epoch 60/100
7000/7000 [==============================] - 1s 164us/step - loss: 0.3949 - acc: 0.8346 - val_loss: 0.3764 - val_acc: 0.8430
Epoch 61/100
7000/7000 [==============================] - 1s 158us/step - loss: 0.3843 - acc: 0.8407 - val_loss: 0.3643 - val_acc: 0.8520
Epoch 62/100
7000/7000 [==============================] - 1s 173us/step - loss: 0.3909 - acc: 0.8393 - val_loss: 0.3683 - val_acc: 0.8497
Epoch 63/100
7000/7000 [==============================] - 1s 157us/step - loss: 0.3853 - acc: 0.8416 - val_loss: 0.3662 - val_acc: 0.8520
Epoch 64/100
7000/7000 [==============================] - 1s 159us/step - loss: 0.3896 - acc: 0.8394 - val_loss: 0.3606 - val_acc: 0.8587
Epoch 65/100
7000/7000 [==============================] - 1s 157us/step - loss: 0.3912 - acc: 0.8363 - val_loss: 0.4006 - val_acc: 0.8543
Epoch 66/100
7000/7000 [==============================] - 1s 160us/step - loss: 0.3882 - acc: 0.8399 - val_loss: 0.3702 - val_acc: 0.8470
Epoch 67/100
7000/7000 [==========

In [36]:
model.predict(X_test)
y_predict=model.predict_classes(X_test)
metrics.accuracy_score(y_test,y_predict)
metrics.confusion_matrix(y_test,y_predict)
cr=metrics.classification_report(y_test,y_predict)
print(cr)

array([[0.45653805],
       [0.22561514],
       [0.09033576],
       ...,
       [0.11526269],
       [0.1473909 ],
       [0.66228366]], dtype=float32)

0.8513333333333334

array([[2299,   80],
       [ 366,  255]], dtype=int64)

              precision    recall  f1-score   support

           0       0.86      0.97      0.91      2379
           1       0.76      0.41      0.53       621

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.81      0.69      0.72      3000
weighted avg       0.84      0.85      0.83      3000

